name: Daniel Czulno
favicon: null
layout_spectrum: 0.76676
typography_spectrum: 0.7813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26232a'
    - '#f8f8f8'
    - '#9b8a76'
    - '#be6121'
    - '#5f624e'
  brandStrength: 0.75
  lightness: 0.40281299292109907
  saturation: 0.6875
  rhythmicContrast: 0.502555287675932
purpose: []
