layout_spectrum: 0.4671955287922174
typography_spectrum: 0.6035113208927214
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.2401287597604096
  lightness: 0.6660119926091284
  saturation: 0.05266550020314753
  rhythmicContrast: 0.6084372794721276
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Daniel Czulno
  email: danielczulno@yahoo.com
name: Daniel Czulno
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Fatherhood, Investing, and Life'
purpose: []
