typography_spectrum: 0.93489
color:
  brandColors:
    - '#010103'
    - '#ecded1'
    - '#7bb9e8'
    - '#373737'
    - '#655b4f'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5242
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Daniel Czulno
  email: danielczulno@yahoo.com
name: Daniel Czulno
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Fatherhood, Investing, and Life'
purpose: []
