name: Daniel Czulno
favicon: null
layout_spectrum: 0.39113764674402773
typography_spectrum: 0.3599092778749764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.727279317099601
  lightness: 0.40281299292109907
  saturation: 0.5948407093528658
  rhythmicContrast: 0.502555287675932
purpose: []
