name: Daniel Czulno
favicon: null
layout_spectrum: 0.76676
typography_spectrum: 0.7813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#ecded1'
    - '#7bb9e8'
    - '#373737'
    - '#655b4f'
  brandStrength: 0.75
  lightness: 0.40281299292109907
  saturation: 0.6875
  rhythmicContrast: 0.502555287675932
purpose: []
